import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCallback } from 'react';
import { useNotifications } from '../../context/NotificationContext';
import NotificationItem from './NotificationItem';
import { Button } from '@raga/shared-ui';
import clsx from 'clsx';
export default function NotificationPanel({ onClose }) {
    const { notifications, unreadCount, markAllAsRead, clearAll } = useNotifications();
    const handleClearAll = useCallback(() => {
        clearAll();
        onClose();
    }, [clearAll, onClose]);
    return (_jsxs("div", { className: clsx('flex flex-col h-full w-full', 'bg-white border-l border-slate-100'), children: [_jsxs("div", { className: "flex items-start justify-between px-5 pt-5 pb-4\n                      border-b border-slate-100 shrink-0", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-sm font-semibold text-slate-800 leading-tight", children: "Notifications" }), _jsx("p", { className: "text-xs text-slate-400 mt-0.5", children: unreadCount > 0 ? `${unreadCount} unread` : 'All caught up' })] }), _jsxs("div", { className: "flex items-center gap-1", children: [unreadCount > 0 && (_jsx(Button, { variant: "ghost", size: "sm", onClick: markAllAsRead, className: "text-xs text-indigo-600 hover:text-indigo-700", children: "Mark all read" })), _jsx("button", { onClick: onClose, "aria-label": "Close notifications", className: "p-1.5 rounded-lg text-slate-400\n                       hover:text-slate-600 hover:bg-slate-100\n                       transition-colors duration-150", children: _jsx(CloseIcon, {}) })] })] }), _jsx("div", { className: "flex-1 overflow-y-auto overscroll-contain", children: notifications.length === 0 ? (_jsx(EmptyState, {})) : (_jsx("ul", { className: "divide-y divide-slate-50", children: notifications.map(n => (_jsx(NotificationItem, { notification: n }, n.id))) })) }), notifications.length > 0 && (_jsx("div", { className: "shrink-0 px-5 py-3 border-t border-slate-100", children: _jsx(Button, { variant: "ghost", size: "sm", fullWidth: true, onClick: handleClearAll, className: "text-xs text-slate-500", children: "Clear all notifications" }) }))] }));
}
// ── Empty state ───────────────────────────────────────────────────
function EmptyState() {
    return (_jsxs("div", { className: "flex flex-col items-center justify-center\n                    h-full min-h-[320px] px-8 gap-4 select-none", children: [_jsxs("div", { className: "relative", children: [_jsx("div", { className: "w-20 h-20 rounded-full bg-slate-50\n                        flex items-center justify-center", children: _jsxs("svg", { viewBox: "0 0 48 48", fill: "none", className: "w-10 h-10 text-slate-300", xmlns: "http://www.w3.org/2000/svg", children: [_jsx("circle", { cx: "24", cy: "24", r: "22", stroke: "currentColor", strokeWidth: "2" }), _jsx("path", { d: "M24 12a8 8 0 00-8 8v4l-2 4h20l-2-4v-4a8\n                     8 0 00-8-8z", stroke: "currentColor", strokeWidth: "1.8", strokeLinejoin: "round", fill: "none" }), _jsx("path", { d: "M21 28a3 3 0 006 0", stroke: "currentColor", strokeWidth: "1.8", strokeLinecap: "round", fill: "none" }), _jsx("text", { x: "30", y: "18", fontSize: "6", fill: "currentColor", fontWeight: "600", opacity: "0.5", children: "z" }), _jsx("text", { x: "33", y: "14", fontSize: "5", fill: "currentColor", fontWeight: "600", opacity: "0.35", children: "z" }), _jsx("text", { x: "35.5", y: "10.5", fontSize: "4", fill: "currentColor", fontWeight: "600", opacity: "0.2", children: "z" })] }) }), _jsx("div", { className: "absolute inset-0 rounded-full border-2\n                        border-dashed border-slate-100 scale-110" })] }), _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "text-sm font-medium text-slate-600", children: "All quiet here" }), _jsx("p", { className: "text-xs text-slate-400 mt-1 leading-relaxed max-w-[200px]", children: "Notifications from patients and the system will appear here." })] })] }));
}
// ── Icons ─────────────────────────────────────────────────────────
const CloseIcon = () => (_jsx("svg", { viewBox: "0 0 16 16", fill: "currentColor", className: "w-4 h-4", children: _jsx("path", { d: "M4.28 3.22a.75.75 0 00-1.06 1.06L6.94 8l-3.72\n             3.72a.75.75 0 101.06 1.06L8 9.06l3.72 3.72a.75.75\n             0 101.06-1.06L9.06 8l3.72-3.72a.75.75 0\n             00-1.06-1.06L8 6.94 4.28 3.22z" }) }));
