import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, } from 'recharts';
export default function AdmissionsTrendChart({ data }) {
    return (_jsxs("div", { className: "bg-white rounded-xl border border-slate-100\n                    shadow-sm p-5", children: [_jsxs("div", { className: "flex items-center justify-between mb-5", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-sm font-semibold text-slate-800", children: "Admissions vs Discharges" }), _jsx("p", { className: "text-xs text-slate-400 mt-0.5", children: "Last 12 months" })] }), _jsxs("div", { className: "flex items-center gap-4 text-xs text-slate-500", children: [_jsxs("span", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-indigo-500" }), "Admissions"] }), _jsxs("span", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-emerald-500" }), "Discharges"] })] })] }), _jsx(ResponsiveContainer, { width: "100%", height: 200, children: _jsxs(AreaChart, { data: data, margin: { top: 5, right: 5, left: -20, bottom: 0 }, children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "admGrad", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#6366f1", stopOpacity: 0.15 }), _jsx("stop", { offset: "95%", stopColor: "#6366f1", stopOpacity: 0 })] }), _jsxs("linearGradient", { id: "disGrad", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#22c55e", stopOpacity: 0.15 }), _jsx("stop", { offset: "95%", stopColor: "#22c55e", stopOpacity: 0 })] })] }), _jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#f1f5f9" }), _jsx(XAxis, { dataKey: "month", tick: { fontSize: 11, fill: '#94a3b8' }, axisLine: false, tickLine: false }), _jsx(YAxis, { tick: { fontSize: 11, fill: '#94a3b8' }, axisLine: false, tickLine: false }), _jsx(Tooltip, { contentStyle: {
                                background: '#1e293b',
                                border: 'none',
                                borderRadius: '8px',
                                color: '#f8fafc',
                                fontSize: '12px',
                                padding: '8px 12px',
                            }, cursor: { stroke: '#e2e8f0', strokeWidth: 1 } }), _jsx(Area, { type: "monotone", dataKey: "admissions", stroke: "#6366f1", strokeWidth: 2, fill: "url(#admGrad)", dot: false, activeDot: { r: 4, fill: '#6366f1' } }), _jsx(Area, { type: "monotone", dataKey: "discharges", stroke: "#22c55e", strokeWidth: 2, fill: "url(#disGrad)", dot: false, activeDot: { r: 4, fill: '#22c55e' } })] }) })] }));
}
